"""
===========================================================
Cloud Secure Hospital Management & Accounting ERP System
Module  : Reports PDF
Version : 3.0
===========================================================
"""

import os

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet

from frontend.printing.invoice_template import InvoiceTemplate


class ReportsPDF:

    def __init__(self):

        self.styles = getSampleStyleSheet()

        self.template = InvoiceTemplate()

    # ==========================================
    # Export Report
    # ==========================================

    def export_report(

        self,

        filename,

        title,

        headers,

        rows

    ):

        pdf = SimpleDocTemplate(

            filename,

            pagesize=A4

        )

        story = []

        story.append(

            self.template.hospital_header()

        )

        story.append(

            self.template.spacer()

        )

        story.append(

            self.template.title(title)

        )

        story.append(

            Spacer(1, 10)

        )

        table_data = [

            headers

        ]

        table_data.extend(rows)

        report_table = Table(table_data)

        report_table.setStyle(

            TableStyle(

                [

                    ("GRID", (0, 0), (-1, -1), 0.5, colors.black),

                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#007ACC")),

                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),

                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),

                    ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

                    ("BACKGROUND", (0, 1), (-1, -1), colors.white),

                    ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                     [colors.white, colors.HexColor("#F5F9FF")])

                ]

            )

        )

        story.append(report_table)

        story.append(Spacer(1, 15))

        # ==========================================
        # Footer
        # ==========================================

        story.append(

            Paragraph(

                "<br/><br/><b>Generated By : Cloud Secure Hospital ERP</b>",

                self.styles["Heading3"]

            )

        )

        from datetime import datetime

        story.append(

            Paragraph(

                f"Generated On : {datetime.now().strftime('%d-%m-%Y %I:%M %p')}<br/><br/>"
                "This is a computer-generated report.",

                self.styles["Normal"]

            )

        )

        story.append(

            Spacer(1, 20)

        )

        # Build PDF

        pdf.build(story)

        return os.path.abspath(filename)